version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
    - frontend

  frontend:
    build:
      context: ./testweb
    ports:
      - "8080:8080"
    volumes:
      - ./testweb:/app